version: '3.7'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/home/docker/comments
    ports:
      - 8010:8000
    env_file:
      - ./.env